### PR TITLE
tftp: fight packet buffer leaks

### PR DESCRIPTION
**Pull request by daniel-k**
`gnrc_pktbuf_release`s needed as mentioned in comments. I want to use your TFTP code for part of my bachelor thesis, so I'm trying to get it working at the moment. So sharing efforts :-)

### CODE REVIEW

**Comment by DipSwitch** [comment]
Oops... sorry about that!

Wouldn't it be a good idea to release the received packet in the functions `int _tftp_do_client_transfer(tftp_context_t *ctxt)` L418 and `int _tftp_server(tftp_context_t *ctxt)` L381? 
That way it can never be forgotten :)

```
if (m.type == GNRC_NETAPI_MSG_TYPE_RCV) {
    gnrc_pktbuf_release((gnrc_pktsnip_t*)m.context.p);
}
```

**Comment by daniel-k** [comment]
> Oops... sorry about that!

No need to be sorry ;) Those pktbuffer leaks are a pain-in-the-ass. I had some fun with them while writing my MAC layer, so I've got an eye for them now.

> Wouldn't it be a good idea to release the received packet in the functions int _tftp_do_client_transfer(tftp_context_t *ctxt) L418 and int _tftp_server(tftp_context_t *ctxt) L381?
> That way it can never be forgotten :)

Definitely! This was my quick-fix. Could be something like this:

``` c
if(msg.type == GNRC_NETAPI_MSG_TYPE_RCV) {
    gnrc_pktbuf_release(msg.content.ptr);
}
```

**Comment by daniel-k** [comment]
@DipSwitch 
See cd1aab4.

**Comment by DipSwitch** [comment]
Nice :) think that fixes all.

**Comment by DipSwitch** [comment]
Can you rebase?

**Comment by daniel-k** [comment]
You mean squash? ;) No need to rebase here I guess.

**Comment by DipSwitch** [comment]
Haha yeah that one :p

**Comment by DipSwitch** [comment]
Thx :) nice work!

**Pull request merged**
